
services:
  web:
    build: .
    # env_file: ./.env
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - app-network

  pgadmin:
    container_name: samsara-pgadmin
    image: dpage/pgadmin4:7.2
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8081:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - database
    networks:
      - app-network

volumes:
  database_data:
  pgadmin:

networks:
  app-network:
    driver: bridge
