<?php

namespace App\Enum;

enum UserRoles:string  {
    case ADMIN = 'ROLE_ADMIN';
    case USER = 'ROLE_USER';
    case AFFILIATE_MANAGER = 'ROLE_AFFILIATE_MANAGER';
    case DIRECTOR = 'ROLE_DIRECTOR';
    case SUPPLIER_REPRESENTATIVE = 'ROLE_SUPPLIER_REPRESENTATIVE';
    case PARTNER_REPRESENTATIVE = 'ROLE_PARTNER_REPRESENTATIVE';
    case LOGIST = 'ROLE_LOGIST';
    case PRODUCTION_MANAGER = 'ROLE_PRODUCTION_MANAGER';
}